// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: animefeed.sql

package data

import (
	"context"
	"strings"
)

const createAnimeEntry = `-- name: CreateAnimeEntry :one
INSERT INTO user_anime_entry (
    user_id,
    name,
    keywords,
    channel_id,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, keywords, channel_id, latest_guid, latest_title, latest_link, latest_published_at, last_notified_at, created_at, updated_at
`

type CreateAnimeEntryParams struct {
	UserID    string  `json:"user_id"`
	Name      string  `json:"name"`
	Keywords  string  `json:"keywords"`
	ChannelID *string `json:"channel_id"`
	CreatedAt int64   `json:"created_at"`
	UpdatedAt int64   `json:"updated_at"`
}

func (q *Queries) CreateAnimeEntry(ctx context.Context, db DBTX, arg CreateAnimeEntryParams) (UserAnimeEntry, error) {
	row := db.QueryRowContext(ctx, createAnimeEntry,
		arg.UserID,
		arg.Name,
		arg.Keywords,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserAnimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Keywords,
		&i.ChannelID,
		&i.LatestGuid,
		&i.LatestTitle,
		&i.LatestLink,
		&i.LatestPublishedAt,
		&i.LastNotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAnimeMatch = `-- name: CreateAnimeMatch :exec
INSERT INTO user_anime_match (
    user_anime_entry_id,
    guid,
    title,
    link,
    published_at,
    created_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAnimeMatchParams struct {
	UserAnimeEntryID int64  `json:"user_anime_entry_id"`
	Guid             string `json:"guid"`
	Title            string `json:"title"`
	Link             string `json:"link"`
	PublishedAt      *int64 `json:"published_at"`
	CreatedAt        int64  `json:"created_at"`
}

func (q *Queries) CreateAnimeMatch(ctx context.Context, db DBTX, arg CreateAnimeMatchParams) error {
	_, err := db.ExecContext(ctx, createAnimeMatch,
		arg.UserAnimeEntryID,
		arg.Guid,
		arg.Title,
		arg.Link,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}

const createProcessedRssEntry = `-- name: CreateProcessedRssEntry :exec
INSERT INTO processed_rss_entry (
    guid,
    title,
    link,
    published_at,
    created_at
)
VALUES (?, ?, ?, ?, ?)
`

type CreateProcessedRssEntryParams struct {
	Guid        string `json:"guid"`
	Title       string `json:"title"`
	Link        string `json:"link"`
	PublishedAt *int64 `json:"published_at"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateProcessedRssEntry(ctx context.Context, db DBTX, arg CreateProcessedRssEntryParams) error {
	_, err := db.ExecContext(ctx, createProcessedRssEntry,
		arg.Guid,
		arg.Title,
		arg.Link,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAnimeEntryOwned = `-- name: DeleteAnimeEntryOwned :execrows
DELETE FROM user_anime_entry
WHERE user_id = ? AND name = ?
`

func (q *Queries) DeleteAnimeEntryOwned(ctx context.Context, db DBTX, userID string, name string) (int64, error) {
	result, err := db.ExecContext(ctx, deleteAnimeEntryOwned, userID, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAnimeSettingsByUser = `-- name: GetAnimeSettingsByUser :one
SELECT user_id, default_channel_id, created_at, updated_at
FROM user_anime_settings
WHERE user_id = ?
`

func (q *Queries) GetAnimeSettingsByUser(ctx context.Context, db DBTX, userID string) (UserAnimeSetting, error) {
	row := db.QueryRowContext(ctx, getAnimeSettingsByUser, userID)
	var i UserAnimeSetting
	err := row.Scan(
		&i.UserID,
		&i.DefaultChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcessedRssEntry = `-- name: GetProcessedRssEntry :one
SELECT guid, title, link, published_at, created_at
FROM processed_rss_entry
WHERE guid = ?
`

func (q *Queries) GetProcessedRssEntry(ctx context.Context, db DBTX, guid string) (ProcessedRssEntry, error) {
	row := db.QueryRowContext(ctx, getProcessedRssEntry, guid)
	var i ProcessedRssEntry
	err := row.Scan(
		&i.Guid,
		&i.Title,
		&i.Link,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasAnimeMatch = `-- name: HasAnimeMatch :one
SELECT EXISTS(
    SELECT 1
    FROM user_anime_match
    WHERE user_anime_entry_id = ? AND guid = ?
)
`

func (q *Queries) HasAnimeMatch(ctx context.Context, db DBTX, userAnimeEntryID int64, guid string) (bool, error) {
	row := db.QueryRowContext(ctx, hasAnimeMatch, userAnimeEntryID, guid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAnimeEntries = `-- name: ListAnimeEntries :many
SELECT id, user_id, name, keywords, channel_id, latest_guid, latest_title, latest_link, latest_published_at, last_notified_at, created_at, updated_at
FROM user_anime_entry
ORDER BY id ASC
`

func (q *Queries) ListAnimeEntries(ctx context.Context, db DBTX) ([]UserAnimeEntry, error) {
	rows, err := db.QueryContext(ctx, listAnimeEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAnimeEntry
	for rows.Next() {
		var i UserAnimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Keywords,
			&i.ChannelID,
			&i.LatestGuid,
			&i.LatestTitle,
			&i.LatestLink,
			&i.LatestPublishedAt,
			&i.LastNotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimeEntriesByUser = `-- name: ListAnimeEntriesByUser :many
SELECT id, user_id, name, keywords, channel_id, latest_guid, latest_title, latest_link, latest_published_at, last_notified_at, created_at, updated_at
FROM user_anime_entry
WHERE user_id = ?
ORDER BY name ASC
`

func (q *Queries) ListAnimeEntriesByUser(ctx context.Context, db DBTX, userID string) ([]UserAnimeEntry, error) {
	rows, err := db.QueryContext(ctx, listAnimeEntriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAnimeEntry
	for rows.Next() {
		var i UserAnimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Keywords,
			&i.ChannelID,
			&i.LatestGuid,
			&i.LatestTitle,
			&i.LatestLink,
			&i.LatestPublishedAt,
			&i.LastNotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessedRssEntriesByGUIDs = `-- name: ListProcessedRssEntriesByGUIDs :many
SELECT guid, title, link, published_at, created_at
FROM processed_rss_entry
WHERE guid IN (/*SLICE:guids*/?)
`

func (q *Queries) ListProcessedRssEntriesByGUIDs(ctx context.Context, db DBTX, guids []string) ([]ProcessedRssEntry, error) {
	query := listProcessedRssEntriesByGUIDs
	var queryParams []interface{}
	if len(guids) > 0 {
		for _, v := range guids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:guids*/?", strings.Repeat(",?", len(guids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:guids*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessedRssEntry
	for rows.Next() {
		var i ProcessedRssEntry
		if err := rows.Scan(
			&i.Guid,
			&i.Title,
			&i.Link,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAnimeMatchesByEntryIDs = `-- name: ListRecentAnimeMatchesByEntryIDs :many
SELECT id, user_anime_entry_id, guid, title, link, published_at, created_at
FROM user_anime_match
WHERE user_anime_entry_id IN (/*SLICE:entry_ids*/?)
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentAnimeMatchesByEntryIDs(ctx context.Context, db DBTX, entryIds []int64, limit int64) ([]UserAnimeMatch, error) {
	query := listRecentAnimeMatchesByEntryIDs
	var queryParams []interface{}
	if len(entryIds) > 0 {
		for _, v := range entryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", strings.Repeat(",?", len(entryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entry_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, limit)
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAnimeMatch
	for rows.Next() {
		var i UserAnimeMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserAnimeEntryID,
			&i.Guid,
			&i.Title,
			&i.Link,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAnimeMatchesByUser = `-- name: ListRecentAnimeMatchesByUser :many
SELECT m.id, m.user_anime_entry_id, m.guid, m.title, m.link, m.published_at, m.created_at
FROM user_anime_match m
JOIN user_anime_entry e ON e.id = m.user_anime_entry_id
WHERE e.user_id = ?
ORDER BY m.created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentAnimeMatchesByUser(ctx context.Context, db DBTX, userID string, limit int64) ([]UserAnimeMatch, error) {
	rows, err := db.QueryContext(ctx, listRecentAnimeMatchesByUser, userID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAnimeMatch
	for rows.Next() {
		var i UserAnimeMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserAnimeEntryID,
			&i.Guid,
			&i.Title,
			&i.Link,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAnimeEntryChannel = `-- name: SetAnimeEntryChannel :execrows
UPDATE user_anime_entry
SET channel_id = ?, updated_at = ?
WHERE user_id = ? AND name = ?
`

type SetAnimeEntryChannelParams struct {
	ChannelID *string `json:"channel_id"`
	UpdatedAt int64   `json:"updated_at"`
	UserID    string  `json:"user_id"`
	Name      string  `json:"name"`
}

func (q *Queries) SetAnimeEntryChannel(ctx context.Context, db DBTX, arg SetAnimeEntryChannelParams) (int64, error) {
	result, err := db.ExecContext(ctx, setAnimeEntryChannel,
		arg.ChannelID,
		arg.UpdatedAt,
		arg.UserID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAnimeEntryLatest = `-- name: UpdateAnimeEntryLatest :exec
UPDATE user_anime_entry
SET latest_guid = ?,
    latest_title = ?,
    latest_link = ?,
    latest_published_at = ?,
    last_notified_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAnimeEntryLatestParams struct {
	LatestGuid        *string `json:"latest_guid"`
	LatestTitle       *string `json:"latest_title"`
	LatestLink        *string `json:"latest_link"`
	LatestPublishedAt *int64  `json:"latest_published_at"`
	LastNotifiedAt    *int64  `json:"last_notified_at"`
	UpdatedAt         int64   `json:"updated_at"`
	ID                int64   `json:"id"`
}

func (q *Queries) UpdateAnimeEntryLatest(ctx context.Context, db DBTX, arg UpdateAnimeEntryLatestParams) error {
	_, err := db.ExecContext(ctx, updateAnimeEntryLatest,
		arg.LatestGuid,
		arg.LatestTitle,
		arg.LatestLink,
		arg.LatestPublishedAt,
		arg.LastNotifiedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertAnimeSettings = `-- name: UpsertAnimeSettings :one
INSERT INTO user_anime_settings (
    user_id,
    default_channel_id,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    default_channel_id = excluded.default_channel_id,
    updated_at = excluded.updated_at
RETURNING user_id, default_channel_id, created_at, updated_at
`

type UpsertAnimeSettingsParams struct {
	UserID           string  `json:"user_id"`
	DefaultChannelID *string `json:"default_channel_id"`
	CreatedAt        int64   `json:"created_at"`
	UpdatedAt        int64   `json:"updated_at"`
}

func (q *Queries) UpsertAnimeSettings(ctx context.Context, db DBTX, arg UpsertAnimeSettingsParams) (UserAnimeSetting, error) {
	row := db.QueryRowContext(ctx, upsertAnimeSettings,
		arg.UserID,
		arg.DefaultChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserAnimeSetting
	err := row.Scan(
		&i.UserID,
		&i.DefaultChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
