// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild_instructions.sql

package data

import (
	"context"
)

const getGuildInstructions = `-- name: GetGuildInstructions :one
SELECT guild_id, instructions, created_at, updated_at
FROM guild_instructions
WHERE guild_id = ?
`

func (q *Queries) GetGuildInstructions(ctx context.Context, db DBTX, guildID string) (GuildInstruction, error) {
	row := db.QueryRowContext(ctx, getGuildInstructions, guildID)
	var i GuildInstruction
	err := row.Scan(
		&i.GuildID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuildInstructions = `-- name: UpsertGuildInstructions :one
INSERT INTO guild_instructions(guild_id, instructions, created_at, updated_at)
VALUES(?, ?, ?, ?)
ON CONFLICT(guild_id) DO UPDATE SET
    instructions = excluded.instructions,
    updated_at = excluded.updated_at
RETURNING guild_id, instructions, created_at, updated_at
`

type UpsertGuildInstructionsParams struct {
	GuildID      string `json:"guild_id"`
	Instructions string `json:"instructions"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertGuildInstructions(ctx context.Context, db DBTX, arg UpsertGuildInstructionsParams) (GuildInstruction, error) {
	row := db.QueryRowContext(ctx, upsertGuildInstructions,
		arg.GuildID,
		arg.Instructions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GuildInstruction
	err := row.Scan(
		&i.GuildID,
		&i.Instructions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
