// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild_flags.sql

package data

import (
	"context"
)

const createGuildFlag = `-- name: CreateGuildFlag :one
INSERT INTO guild_flags(guild_id, name, description, guidance, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?)
RETURNING id, guild_id, name, description, guidance, created_at, updated_at
`

type CreateGuildFlagParams struct {
	GuildID     string `json:"guild_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Guidance    string `json:"guidance"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateGuildFlag(ctx context.Context, db DBTX, arg CreateGuildFlagParams) (GuildFlag, error) {
	row := db.QueryRowContext(ctx, createGuildFlag,
		arg.GuildID,
		arg.Name,
		arg.Description,
		arg.Guidance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GuildFlag
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.Guidance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuildFlag = `-- name: DeleteGuildFlag :execrows
DELETE FROM guild_flags
WHERE id = ? AND guild_id = ?
`

func (q *Queries) DeleteGuildFlag(ctx context.Context, db DBTX, iD int64, guildID string) (int64, error) {
	result, err := db.ExecContext(ctx, deleteGuildFlag, iD, guildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listGuildFlagsByGuild = `-- name: ListGuildFlagsByGuild :many
SELECT id, guild_id, name, description, guidance, created_at, updated_at
FROM guild_flags
WHERE guild_id = ?
ORDER BY id
`

func (q *Queries) ListGuildFlagsByGuild(ctx context.Context, db DBTX, guildID string) ([]GuildFlag, error) {
	rows, err := db.QueryContext(ctx, listGuildFlagsByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildFlag
	for rows.Next() {
		var i GuildFlag
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Description,
			&i.Guidance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuildFlag = `-- name: UpdateGuildFlag :one
UPDATE guild_flags
SET description = ?, guidance = ?, updated_at = ?
WHERE id = ? AND guild_id = ?
RETURNING id, guild_id, name, description, guidance, created_at, updated_at
`

type UpdateGuildFlagParams struct {
	Description string `json:"description"`
	Guidance    string `json:"guidance"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          int64  `json:"id"`
	GuildID     string `json:"guild_id"`
}

func (q *Queries) UpdateGuildFlag(ctx context.Context, db DBTX, arg UpdateGuildFlagParams) (GuildFlag, error) {
	row := db.QueryRowContext(ctx, updateGuildFlag,
		arg.Description,
		arg.Guidance,
		arg.UpdatedAt,
		arg.ID,
		arg.GuildID,
	)
	var i GuildFlag
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.Guidance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
