// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_message_logs.sql

package data

import (
	"context"
)

const createLLMMessageLog = `-- name: CreateLLMMessageLog :one
INSERT INTO llm_message_logs(
    guild_id,
    channel_id,
    user_id,
    message_id,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    llm_turns,
    tool_calls,
    latency_ms,
    status,
    error,
    created_at
)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, guild_id, channel_id, user_id, message_id, prompt_tokens, completion_tokens, total_tokens, llm_turns, tool_calls, latency_ms, status, error, created_at
`

type CreateLLMMessageLogParams struct {
	GuildID          *string `json:"guild_id"`
	ChannelID        string  `json:"channel_id"`
	UserID           string  `json:"user_id"`
	MessageID        string  `json:"message_id"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	TotalTokens      int64   `json:"total_tokens"`
	LlmTurns         int64   `json:"llm_turns"`
	ToolCalls        int64   `json:"tool_calls"`
	LatencyMs        int64   `json:"latency_ms"`
	Status           string  `json:"status"`
	Error            string  `json:"error"`
	CreatedAt        int64   `json:"created_at"`
}

func (q *Queries) CreateLLMMessageLog(ctx context.Context, db DBTX, arg CreateLLMMessageLogParams) (LlmMessageLog, error) {
	row := db.QueryRowContext(ctx, createLLMMessageLog,
		arg.GuildID,
		arg.ChannelID,
		arg.UserID,
		arg.MessageID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LlmTurns,
		arg.ToolCalls,
		arg.LatencyMs,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
	)
	var i LlmMessageLog
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.UserID,
		&i.MessageID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.LlmTurns,
		&i.ToolCalls,
		&i.LatencyMs,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listLLMMessageLogsByGuild = `-- name: ListLLMMessageLogsByGuild :many
SELECT id, guild_id, channel_id, user_id, message_id, prompt_tokens, completion_tokens, total_tokens, llm_turns, tool_calls, latency_ms, status, error, created_at
FROM llm_message_logs
WHERE guild_id = ?
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListLLMMessageLogsByGuild(ctx context.Context, db DBTX, guildID *string, limit int64) ([]LlmMessageLog, error) {
	rows, err := db.QueryContext(ctx, listLLMMessageLogsByGuild, guildID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmMessageLog
	for rows.Next() {
		var i LlmMessageLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.UserID,
			&i.MessageID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LlmTurns,
			&i.ToolCalls,
			&i.LatencyMs,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
