// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package data

type ProcessedRssEntry struct {
	Guid        string `json:"guid"`
	Title       string `json:"title"`
	Link        string `json:"link"`
	PublishedAt *int64 `json:"published_at"`
	CreatedAt   int64  `json:"created_at"`
}

type Reminder struct {
	ID        int64   `json:"id"`
	UserID    string  `json:"user_id"`
	ChannelID string  `json:"channel_id"`
	GuildID   *string `json:"guild_id"`
	Message   string  `json:"message"`
	Schedule  string  `json:"schedule"`
	AtTime    *string `json:"at_time"`
	NextRun   int64   `json:"next_run"`
	CreatedAt int64   `json:"created_at"`
	UpdatedAt int64   `json:"updated_at"`
}

type UserAnimeEntry struct {
	ID                int64   `json:"id"`
	UserID            string  `json:"user_id"`
	Name              string  `json:"name"`
	Keywords          string  `json:"keywords"`
	ChannelID         *string `json:"channel_id"`
	LatestGuid        *string `json:"latest_guid"`
	LatestTitle       *string `json:"latest_title"`
	LatestLink        *string `json:"latest_link"`
	LatestPublishedAt *int64  `json:"latest_published_at"`
	LastNotifiedAt    *int64  `json:"last_notified_at"`
	CreatedAt         int64   `json:"created_at"`
	UpdatedAt         int64   `json:"updated_at"`
}

type UserAnimeMatch struct {
	ID               int64  `json:"id"`
	UserAnimeEntryID int64  `json:"user_anime_entry_id"`
	Guid             string `json:"guid"`
	Title            string `json:"title"`
	Link             string `json:"link"`
	PublishedAt      *int64 `json:"published_at"`
	CreatedAt        int64  `json:"created_at"`
}

type UserAnimeSetting struct {
	UserID           string  `json:"user_id"`
	DefaultChannelID *string `json:"default_channel_id"`
	CreatedAt        int64   `json:"created_at"`
	UpdatedAt        int64   `json:"updated_at"`
}
