// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

type Reminder struct {
	ID        int64   `json:"id"`
	UserID    string  `json:"user_id"`
	ChannelID string  `json:"channel_id"`
	GuildID   *string `json:"guild_id"`
	Message   string  `json:"message"`
	Schedule  string  `json:"schedule"`
	AtTime    *string `json:"at_time"`
	NextRun   int64   `json:"next_run"`
	CreatedAt int64   `json:"created_at"`
	UpdatedAt int64   `json:"updated_at"`
}
