// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pagemonitor.sql

package data

import (
	"context"
)

const createPageMonitor = `-- name: CreatePageMonitor :one
INSERT INTO page_monitors(user_id, channel_id, guild_id, url, label, selector, last_status, content_hash, last_content, check_interval, next_check, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, channel_id, guild_id, url, label, selector, last_status, content_hash, last_content, check_interval, next_check, created_at, updated_at
`

type CreatePageMonitorParams struct {
	UserID        string  `json:"user_id"`
	ChannelID     string  `json:"channel_id"`
	GuildID       *string `json:"guild_id"`
	Url           string  `json:"url"`
	Label         string  `json:"label"`
	Selector      string  `json:"selector"`
	LastStatus    string  `json:"last_status"`
	ContentHash   string  `json:"content_hash"`
	LastContent   string  `json:"last_content"`
	CheckInterval int64   `json:"check_interval"`
	NextCheck     int64   `json:"next_check"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

type CreatePageMonitorRow struct {
	ID            int64   `json:"id"`
	UserID        string  `json:"user_id"`
	ChannelID     string  `json:"channel_id"`
	GuildID       *string `json:"guild_id"`
	Url           string  `json:"url"`
	Label         string  `json:"label"`
	Selector      string  `json:"selector"`
	LastStatus    string  `json:"last_status"`
	ContentHash   string  `json:"content_hash"`
	LastContent   string  `json:"last_content"`
	CheckInterval int64   `json:"check_interval"`
	NextCheck     int64   `json:"next_check"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

func (q *Queries) CreatePageMonitor(ctx context.Context, db DBTX, arg CreatePageMonitorParams) (CreatePageMonitorRow, error) {
	row := db.QueryRowContext(ctx, createPageMonitor,
		arg.UserID,
		arg.ChannelID,
		arg.GuildID,
		arg.Url,
		arg.Label,
		arg.Selector,
		arg.LastStatus,
		arg.ContentHash,
		arg.LastContent,
		arg.CheckInterval,
		arg.NextCheck,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreatePageMonitorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.GuildID,
		&i.Url,
		&i.Label,
		&i.Selector,
		&i.LastStatus,
		&i.ContentHash,
		&i.LastContent,
		&i.CheckInterval,
		&i.NextCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePageMonitor = `-- name: DeletePageMonitor :execrows
DELETE FROM page_monitors WHERE id = ? AND user_id = ?
`

func (q *Queries) DeletePageMonitor(ctx context.Context, db DBTX, iD int64, userID string) (int64, error) {
	result, err := db.ExecContext(ctx, deletePageMonitor, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDuePageMonitors = `-- name: ListDuePageMonitors :many
SELECT id, user_id, channel_id, guild_id, url, label, selector, last_status, content_hash, last_content, check_interval, next_check, created_at, updated_at
FROM page_monitors
WHERE next_check <= ?
ORDER BY next_check ASC
LIMIT ?
`

type ListDuePageMonitorsRow struct {
	ID            int64   `json:"id"`
	UserID        string  `json:"user_id"`
	ChannelID     string  `json:"channel_id"`
	GuildID       *string `json:"guild_id"`
	Url           string  `json:"url"`
	Label         string  `json:"label"`
	Selector      string  `json:"selector"`
	LastStatus    string  `json:"last_status"`
	ContentHash   string  `json:"content_hash"`
	LastContent   string  `json:"last_content"`
	CheckInterval int64   `json:"check_interval"`
	NextCheck     int64   `json:"next_check"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

func (q *Queries) ListDuePageMonitors(ctx context.Context, db DBTX, nextCheck int64, limit int64) ([]ListDuePageMonitorsRow, error) {
	rows, err := db.QueryContext(ctx, listDuePageMonitors, nextCheck, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDuePageMonitorsRow
	for rows.Next() {
		var i ListDuePageMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.GuildID,
			&i.Url,
			&i.Label,
			&i.Selector,
			&i.LastStatus,
			&i.ContentHash,
			&i.LastContent,
			&i.CheckInterval,
			&i.NextCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageMonitorsByUser = `-- name: ListPageMonitorsByUser :many
SELECT id, user_id, channel_id, guild_id, url, label, selector, last_status, content_hash, last_content, check_interval, next_check, created_at, updated_at
FROM page_monitors
WHERE user_id = ?
ORDER BY created_at ASC
`

type ListPageMonitorsByUserRow struct {
	ID            int64   `json:"id"`
	UserID        string  `json:"user_id"`
	ChannelID     string  `json:"channel_id"`
	GuildID       *string `json:"guild_id"`
	Url           string  `json:"url"`
	Label         string  `json:"label"`
	Selector      string  `json:"selector"`
	LastStatus    string  `json:"last_status"`
	ContentHash   string  `json:"content_hash"`
	LastContent   string  `json:"last_content"`
	CheckInterval int64   `json:"check_interval"`
	NextCheck     int64   `json:"next_check"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

func (q *Queries) ListPageMonitorsByUser(ctx context.Context, db DBTX, userID string) ([]ListPageMonitorsByUserRow, error) {
	rows, err := db.QueryContext(ctx, listPageMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPageMonitorsByUserRow
	for rows.Next() {
		var i ListPageMonitorsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.GuildID,
			&i.Url,
			&i.Label,
			&i.Selector,
			&i.LastStatus,
			&i.ContentHash,
			&i.LastContent,
			&i.CheckInterval,
			&i.NextCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePageMonitorContent = `-- name: UpdatePageMonitorContent :exec
UPDATE page_monitors SET last_status = ?, content_hash = ?, last_content = ?, next_check = ?, updated_at = ? WHERE id = ?
`

type UpdatePageMonitorContentParams struct {
	LastStatus  string `json:"last_status"`
	ContentHash string `json:"content_hash"`
	LastContent string `json:"last_content"`
	NextCheck   int64  `json:"next_check"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdatePageMonitorContent(ctx context.Context, db DBTX, arg UpdatePageMonitorContentParams) error {
	_, err := db.ExecContext(ctx, updatePageMonitorContent,
		arg.LastStatus,
		arg.ContentHash,
		arg.LastContent,
		arg.NextCheck,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
