// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: typesafe_classification_logs.sql

package data

import (
	"context"
)

const createTypeSafeClassificationLog = `-- name: CreateTypeSafeClassificationLog :one
INSERT INTO typesafe_classification_logs(
    guild_id,
    channel_id,
    user_id,
    model,
    request_state,
    request_questions,
    response_answers,
    selected_tools,
    input_tokens,
    output_tokens,
    latency_ms,
    status,
    error,
    created_at,
    message_id,
    matched_flags,
    kind
)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, guild_id, channel_id, user_id, model, request_state, request_questions, response_answers, selected_tools, input_tokens, output_tokens, latency_ms, status, error, created_at, message_id, matched_flags, kind
`

type CreateTypeSafeClassificationLogParams struct {
	GuildID          *string `json:"guild_id"`
	ChannelID        string  `json:"channel_id"`
	UserID           string  `json:"user_id"`
	Model            string  `json:"model"`
	RequestState     string  `json:"request_state"`
	RequestQuestions string  `json:"request_questions"`
	ResponseAnswers  string  `json:"response_answers"`
	SelectedTools    string  `json:"selected_tools"`
	InputTokens      int64   `json:"input_tokens"`
	OutputTokens     int64   `json:"output_tokens"`
	LatencyMs        int64   `json:"latency_ms"`
	Status           string  `json:"status"`
	Error            string  `json:"error"`
	CreatedAt        int64   `json:"created_at"`
	MessageID        string  `json:"message_id"`
	MatchedFlags     string  `json:"matched_flags"`
	Kind             string  `json:"kind"`
}

func (q *Queries) CreateTypeSafeClassificationLog(ctx context.Context, db DBTX, arg CreateTypeSafeClassificationLogParams) (TypesafeClassificationLog, error) {
	row := db.QueryRowContext(ctx, createTypeSafeClassificationLog,
		arg.GuildID,
		arg.ChannelID,
		arg.UserID,
		arg.Model,
		arg.RequestState,
		arg.RequestQuestions,
		arg.ResponseAnswers,
		arg.SelectedTools,
		arg.InputTokens,
		arg.OutputTokens,
		arg.LatencyMs,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.MessageID,
		arg.MatchedFlags,
		arg.Kind,
	)
	var i TypesafeClassificationLog
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.UserID,
		&i.Model,
		&i.RequestState,
		&i.RequestQuestions,
		&i.ResponseAnswers,
		&i.SelectedTools,
		&i.InputTokens,
		&i.OutputTokens,
		&i.LatencyMs,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.MessageID,
		&i.MatchedFlags,
		&i.Kind,
	)
	return i, err
}

const listTypeSafeClassificationLogsByGuild = `-- name: ListTypeSafeClassificationLogsByGuild :many
SELECT id, guild_id, channel_id, user_id, model, request_state, request_questions, response_answers, selected_tools, input_tokens, output_tokens, latency_ms, status, error, created_at, message_id, matched_flags, kind
FROM typesafe_classification_logs
WHERE guild_id = ?
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListTypeSafeClassificationLogsByGuild(ctx context.Context, db DBTX, guildID *string, limit int64) ([]TypesafeClassificationLog, error) {
	rows, err := db.QueryContext(ctx, listTypeSafeClassificationLogsByGuild, guildID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypesafeClassificationLog
	for rows.Next() {
		var i TypesafeClassificationLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.UserID,
			&i.Model,
			&i.RequestState,
			&i.RequestQuestions,
			&i.ResponseAnswers,
			&i.SelectedTools,
			&i.InputTokens,
			&i.OutputTokens,
			&i.LatencyMs,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.MessageID,
			&i.MatchedFlags,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
