// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package data

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, timezone, created_at, updated_at
FROM user_settings
WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, db DBTX, userID string) (UserSetting, error) {
	row := db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTimezone = `-- name: UpsertUserTimezone :one
INSERT INTO user_settings(user_id, timezone, created_at, updated_at)
VALUES(?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    timezone = excluded.timezone,
    updated_at = excluded.updated_at
RETURNING user_id, timezone, created_at, updated_at
`

type UpsertUserTimezoneParams struct {
	UserID    string `json:"user_id"`
	Timezone  string `json:"timezone"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertUserTimezone(ctx context.Context, db DBTX, arg UpsertUserTimezoneParams) (UserSetting, error) {
	row := db.QueryRowContext(ctx, upsertUserTimezone,
		arg.UserID,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
